// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_fastr_TMBExports
#include <TMB.hpp>
#include "factor_model_eff.hpp"
#include "factor_model_parallel.hpp"
#include "factor_model.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "factor_model_eff") {
    return factor_model_eff(this);
  } else if(model == "factor_model_parallel") {
    return factor_model_parallel(this);
  } else if(model == "factor_model") {
    return factor_model(this);
  } else {
    error("Unknown model.");
  }
  return 0;
}
